#
# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
#

copyright: Copyright (c) Mainflux
repo_url: https://github.com/mainflux/mainflux
site_description: Mainflux IoT System
site_name: Mainflux
site_url: https://docs.mainflux.io
edit_uri: ""
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  # Core
  - Entities: entities.md
  - API: api.md
  - CLI: cli.md
  - Authentication: authentication.md
  - Authorization: authorization.md
  - Security: security.md
  - Messaging: messaging.md
  - Events: events.md
  # Edge
  - Edge: edge.md
  # Addons
  - Certs: certs.md
  - Bootstrap: bootstrap.md
  - LoRa: lora.md
  - OPC-UA: opcua.md
  - Provision: provision.md
  - Storage: storage.md
  - Twins: twins.md
  # Observability
  - Tracing: tracing.md
  # Utilities
  - Developer's Guide: dev-guide.md
  - Kubernetes: kubernetes.md
  - Benchmark: benchmark.md
